permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Rakesh Kumar Soham
url: exzrion.me
description: A fantastic blog that is fantastic.
twitter: exzrion
instagram: exzrion
youtube: channel/UCBu8BMX8AthCunNZcKHDS0g
